apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gjt25anom-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gjt25anom-nodejs 
  name: gjt25anom-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: gjt25anom-nodejs 
